# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_remove_profile_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Areas',
        ),
        migrations.DeleteModel(
            name='Cities',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
