# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 19:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travelapp', '0005_auto_20170703_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stay', models.IntegerField()),
                ('food', models.IntegerField()),
                ('travelling_charges', models.IntegerField()),
                ('offer_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travelling_date', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('no_of_persons', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('no_of_days', models.IntegerField()),
                ('ratings', models.FloatField(blank=True, default=None, null=True)),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.Area')),
                ('cityid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.City')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('packageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.Packages')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='placemap',
            name='stateid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.State'),
        ),
        migrations.AddField(
            model_name='packages',
            name='mapid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.PlaceMap'),
        ),
        migrations.AddField(
            model_name='booking',
            name='packageid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.Packages'),
        ),
        migrations.AddField(
            model_name='booking',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amount',
            name='packageid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.Packages'),
        ),
    ]
