# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0006_auto_20170703_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
