# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0008_packages_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amount',
            name='packageid',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='packageid',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='mapid',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='packageid',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='userid',
        ),
        migrations.DeleteModel(
            name='Amount',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Packages',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
