# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0010_auto_20170705_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='image',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
