# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0011_state_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='travelling_charges',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
